#!/bin/bash
#
# Routines to automatically or manually enable hdd leds.
#
# Copyright (C) 2016 Sergi Casbas <sergi@casbas.cat>
#
# This file is licensed under the terms of the GNU General Public
# License version 2.  This program is licensed "as is" without any
# warranty of any kind, whether express or implied.

# Set default value for local variables.
if [ -z "$LEDSTATUS_TMP"]; then LEDSTATUS_TMP="/run/dns-nas-utils/leds"; fi
if [ -z "$LEDPATH"]; then LEDPATH="/sys/devices/gpio-leds/leds/dns320:orange:\$1/brightness"; fi

# Prepare temporary folders and files
mkdir -p $LEDSTATUS_TMP
touch "$LEDSTATUS_TMP/sda"
touch "$LEDSTATUS_TMP/sdb"
touch "$LEDSTATUS_TMP/sdc"

# Set a led value. ($1 is the device, $2 the value)
function set_led
{
	echo $2 > "$(eval echo $LEDPATH)"
}

# Light a led if required ($1 is the block device sd?, $2 is the led device).
function blink_led
{
	# Only execute the routine if the device exists.
	if [ -e "/dev/$1" ]; then
		# Compare current status with saved status, if are different blink de light.
		if [ "$(cat /sys/block/$1/stat)" != "$(cat $LEDSTATUS_TMP/$1)" ]; then
			cat /sys/block/$1/stat > $LEDSTATUS_TMP/$1
			set_led $2 255 & 
		else 
			set_led $2 0 &
		fi
	fi
}

# Do all leds to blink if required
function blink_leds
{
	blink_led sda l_hdd &
	blink_led sdb r_hdd &
	blink_led sdc usb &
}

# Reset the current value for all disks.
function reset_leds
{
	set_led l_hdd 0 &
	set_led r_hdd 0 &
	set_led usb 0 &
} 

# Test routines to check leds.
function test
{
	while true; 
	do
		blink_leds
		sleep 1
	done
}
test
