#!/bin/bash
#
# Send diskstatus dlink DNS-320's microcontroller
#
# Copyright (C) 2016 Sergi Casbas <sergi@casbas.cat>
#
# This file is licensed under the terms of the GNU General Public
# License version 2.  This program is licensed "as is" without any
# warranty of any kind, whether express or implied.

old_status=""

while true; do
	curr_status="$(hdparm -C /dev/sdb | grep state)"
	if [ "$curr_status" != "$old_status" ]; then
		old_status="$curr_status"
		echo "diskstatus: $(date) $old_status" > /dev/kmsg
	fi
	sleep 10
done
