#!/bin/bash
# 
# Daemon to control some hardware of dns-320/325
# For now it handle fanspeed, diskstatus and hdd-leds
#
# Copyright (C) 2016 Sergi Casbas <sergi@casbas.cat>
#
# This file is licensed under the terms of the GNU General Public
# License version 2.  This program is licensed "as is" without any
# warranty of any kind, whether express or implied.

# Daemon default values (can be overrided by config file)
frequency=0.75
low_thresh=45
high_thresh=50
hysteresis=2
tmppath="/run/dns-nas-utils/"

# Clean tmppath if exists.
rm -r "$tmppath" 2>/dev/null

# Default devices (are for a dns320).
fan_device="/sys/devices/gpio_fan/hwmon/hwmon0/fan1_target"
led_device="/sys/devices/gpio-leds/leds/dns320:orange:\$1/brightness"

# Load configuration variables
source /etc/dns-nas-utils.conf

# Include code of external libraries
source /usr/lib/dns-nas-utils/diskstatus
source /usr/lib/dns-nas-utils/hdd-leds
source /usr/lib/dns-nas-utils/fanspeed

# Main bucle to process different tools in different frequencies.
# There is a bucle with a frequency 10 times higher than low frequency.
while true; 
do
	# Low frequency iteration.
	# Show diskstatus when required in kernel messages.
	diskstatus sda
	diskstatus sdb
	diskstatus sdc

	# Check system temp and set fan speed.
	set_fanspeed

	# High frequency bucle iteration.
	for i in `seq 1 10`;
	do
		set_leds # set hdd leds if required.
		sleep $frequency
	done
done
