#!/bin/bash

# Daemon default values (can be overrided by config file)
frequency=0.75
low_thresh=45
high_thresh=50
hysteresis=2
tmppath="/run/dns-nas-utils/"

# Default devices.
fan_device="/sys/devices/gpio_fan/hwmon/hwmon0/fan1_target"
led_device="/sys/devices/gpio-leds/leds/dns320:orange:\$1/brightness"

# Load configuration variables
source /etc/dns-nas-utils.conf

# Include code of external libraries
source ../lib/diskstatus
source ../lib/hdd_leds
source ../lib/fanspeed

# Main bucle to process different tools in different frequencies.
# There is a bucle with a frequency 10 times higher than low frequency.
while true; 
do
	# Low frequency iteration.
	# Show diskstatus when required in kernel messages.
	diskstatus sda
	diskstatus sdb
	diskstatus sdc

	# Check system temp and set fan speed.
	set_fanspeed

	# High frequency bucle iteration.
	for i in `seq 1 10`;
	do
		set_leds # set hdd leds if required.
		sleep $frequency
	done
done
