#!/bin/sh

# Setup parameters. Many of them must be moved to a general config file
low_thresh=45
high_thresh=50
hysteresis=2
speed=6000
fan_device=/sys/devices/gpio_fan/hwmon/hwmon0/fan1_target
sleep_time=10

# Set fan to maxium speed for safety. If the script crash at least the fan runs at max.
echo $speed > $fan_device

debug() { :; }

# Fetch all useful temperature readings
while true; do
  debug -n "Temperatures: "
  temp=0
  temps="$(/usr/bin/dns_temp)"

  for t in $temps; do
    debug -n "$t "
    [ $temp -lt $t ] && temp=$t
  done
  debug "\nMaximum temperature: $temp"

  if [ $temp -lt $((low_thresh - hysteresis)) ]; then
    speed=0
  elif [ $temp -lt $low_thresh ]; then
    [ $speed -gt 3000 ] && speed=3000
  elif [ $temp -lt $((high_thresh - hysteresis)) ]; then
    speed=3000
  elif [ $temp -lt $high_thresh ]; then
    [ $speed -lt 3000 ] && speed=3000
  else
    speed=6000
  fi

  # If the current speed is not equal to the desired speed, change it an show messages.
  if [ $speed -ne "$(cat $fan_device)" ]; then
    echo $speed > $fan_device
    echo "fan-daemon: $(date) Current temp is $temp change fan speed to $speed RPM" > /dev/kmsg
    debug "fan-daemon: $(date) Current temp is $temp change fan speed to $speed RPM"
  fi

  sleep $sleep_time
done
